### ISSUE TITLE
Dependency requires core library desugaring to be enabled

### ISSUE THREAD

**Issue by Monabr** [TeamHubApp/firebase-kotlin-sdk#610]
```
Dependency 'dev.gitlive:firebase-config-android-debug:2.0.0' requires core library desugaring to be enabled
           for :shared.
```

I believe this should be fixed.

**Comment by Reedyuk** [comment]
Can you post your build gradle, sounds like you might be adding the dependancy incorrectly.

**Comment by Reedyuk** [comment]
What version of the JDK are you targeting? just wondering if its an issue with an older version being used?

**Comment by Reedyuk** [comment]
Just for reference, when you enable this property, does your project work? 
Sorry, i have not come across this issue before, so its interested to see. 
I think this only affects users who are using Android Build tools 4.x.x
I have been using 7.x.x and never came across this.

**Comment by Reedyuk** [comment]
gradle is fine, my guess is you have this somewhere:

```
com.android.tools.build
```

And this is version 4.x.x

You highlight that maybe what we need is an example KMP(with compose) that uses the library.

**Comment by Reedyuk** [comment]
Whats your min android version you are targeting?

**Comment by Reedyuk** [comment]
This seems to shed some light:
https://medium.com/androiddevelopers/support-for-newer-java-language-apis-bca79fc8ef65
Looks to me like its more related to android than it is this project. I would imagine you would have to add that property for any other libs.

**Comment by Reedyuk** [comment]
ok thanks for the report

**Comment by Daeda88** [comment]
Desugaring is required for the config module as of #553 @Reedyuk and @Monabr due to the use of Kotlinx datetime which requires it as well. Only core library desugaring is required https://github.com/Kotlin/kotlinx-datetime?tab=readme-ov-file#using-in-your-projects

**Comment by Daeda88** [comment]
Did some digging around and it seems fine to just disable core library desugaring on the module itself. Should only be added on the app implementing the SDK. See #618
